CREATE OR REPLACE TRIGGER EXPENSE_ID_TRG
  BEFORE INSERT ON EXPENSE              
  FOR EACH ROW 
BEGIN  
  IF :NEW.EXPENSE_ID IS NULL
  THEN SELECT CONCAT('EX_',TO_CHAR(SYSDATE, 'YYMMDDHH24MISS'))
    INTO :NEW.EXPENSE_ID FROM DUAL;
  END IF;
END;


CREATE OR REPLACE TRIGGER COMBINED_RANK_TRG
  AFTER INSERT OR DELETE OR UPDATE OF RATING ON MEMBER
BEGIN
  UPDATE MEMBER
  SET RANK = (
    SELECT RANK
    FROM (SELECT RANK() OVER(ORDER BY RATING DESC) "RANK",
    MEMBER.USERNAME "USERNM"
    FROM MEMBER, USER_PROFILE
    WHERE USER_PROFILE.USERNAME=MEMBER.USERNAME)
    WHERE USERNAME=USERNM
  );
END;

DROP TRIGGER COMBINED_RANK_TRG;

DELETE FROM MEMBER WHERE USERNAME='nwrnnnkhn';
INSERT INTO MEMBER (USERNAME,TEAM_NAME,STUDENT_ID,DEPT,REWARD_POINT,RATING) VALUES ('nwrnnnkhn', 'MIST_Braindead', '201914006', 'CSE', '41', '158.9');