CREATE OR REPLACE VIEW PROFILE AS  
SELECT 
USERNAME,
NAME,
EMAIL,
DATE_OF_BIRTH,
PASSWORD,
CONTACT_NO,
GENDER,
TSHIRT_SIZE,
U.ADDRESS.HOUSE HOUSE,
U.ADDRESS.STREET STREET,
U.ADDRESS.CITY CITY,
U.ADDRESS.HOUSE||', '||U.ADDRESS.STREET||', '||U.ADDRESS.CITY ADDRESS
FROM USER_PROFILE U;

CREATE OR REPLACE VIEW REWARD_STOCK AS 
SELECT
REWARD_NAME,
CATEGORY,
COUNT(REWARD_NAME) STOCK,
AVG(REQUIRED_POINTS) PRICE
FROM REWARD
WHERE ORDER_STATUS='Available'
GROUP BY REWARD_NAME, CATEGORY;
